### ISSUE TITLE
Problems in mmgenome2 with own dataset

### ISSUE THREAD

**Issue by khuch123** [KasperSkytte/mmgenome2#11]
Initially, the error was "Error in .Call2("new_input_filexp", filepath, PACKAGE = "XVector") : 
  cannot open file 'data/assembly.fa", then when the path was provided it gave the following error:

"Error: The assembly contains duplicate sequence names"

Please help at the earliest.

Regards

**Comment by khuch123** [comment]
Sorry that was my mistake, I rectified it now.

But the only thing I am again struggling with is mmplot, it says loading
required package: shiny, for long it shows this command.

Also, where do we get these values from 7.2, 16.2, 25.2 etc?

selection <- data.frame(cov_C13.11.25 = c(7.2, 16.2, 25.2, 23.3, 10.1),
                        cov_C14.01.09 = c(47, 77, 52.8, 29.5, 22.1))

Please help at the earliest

**Comment by KasperSkytte** [comment]
`shiny` is required, so it loads it. Have a look at the get started guide [here](https://kasperskytte.github.io/mmgenome2/articles/mmgenome2.html). It's coverage values

**Comment by khuch123** [comment]
Yes sir, I understood that but how for these specific values, sorry for
multiple posts.

**Comment by KasperSkytte** [comment]
You get the coordinates by using the locator feature to extract scaffolds of interest. I assume you got those values from the examples, so it's just that, example points.

**Comment by khuch123** [comment]
Thank you very much for the help.

Thank you very much once again.

Please be there to always help us.


Much regards and wishes

**Comment by KasperSkytte** [comment]
You're welcome
