### ISSUE TITLE
allow the user to specify the k-mer size in mmload

### ISSUE THREAD

**Issue by Kirk3gaard** [KasperSkytte/mmgenome2#15]
It could be relevant for some users to specify a k-mer size that is different from 4 when running mmload

https://bioinfologics.github.io/post/2018/09/17/k-mer-counting-part-i-introduction/

**Comment by KasperSkytte** [comment]
Fixed in https://github.com/KasperSkytte/mmgenome2/commit/11205ba864564038fc15488e4c6284c71a37db46
