### ISSUE TITLE
Can you put a link in the home page about where the data for the example comes from?

### ISSUE THREAD

**Issue by btemperton** [KasperSkytte/mmgenome2#21]
Hi there,
I'm hoping to use this mmgenome2 to teach the basics of metagenomics to undergrads in an upcoming workshop, and I wondered if you would be able to tell me where the data for the `mmgenome2` data object came from? I'm also keen to get hold of the short read data that generated the dataset, so I can walk them through how to make the coverage calculations (but I'm guessing I will be able to grab that once I know which paper it was from).

Great tool!

Best wishes,
Ben

**Comment by KasperSkytte** [comment]
Hi Ben! I'll get back to you today or monday, it should be possible to get the data.

**Comment by KasperSkytte** [comment]
Hi again Ben!

Thank you for using `mmgenome2` for teaching. The data is from the article [Albertsen et al., 2013](https://www.nature.com/articles/nbt.2579#accessions), so you can find the raw sequencing data at NCBI with the accession numbers described there.

Regards
Kasper

**Comment by KasperSkytte** [comment]
And I should probably update the get started guide to include the reference tool, thanks for pointing it out.

**Comment by btemperton** [comment]
Thanks Kasper,

I’m a bit confused. The coverage objects in the mmgenome2 data object have names like `C13.11.14`, `C13.11.25`, `C13.12.03` and `C14.01.09` (which suggests 4 samples), yet the Albertsen paper only had hot phenol and FastDNA extraction samples.

What am I missing?

Cheers,
Ben

**Comment by KasperSkytte** [comment]
Hi again!

You're right, it's actually not the same data. It's from 4 digester slurry samples which were sequenced in early 2014, just to serve as example data. So it's not published data, and may take some effort to find on our servers. Is it okay for you to just use the data from the article instead? I see it would be nice to have the same data as in the get started guide, but you could just demonstrate how to generate it using that from the article instead, but use the [figshare](https://figshare.com/articles/mmgenome2_example_data/6115655) data when using mmgenome2.

Regards
Kasper

**Comment by btemperton** [comment]
Hi Kaspar,

Yep of course. You might want to add how the coverage and mapped.sam was created for those samples to the `mmgenome2` instructions, so people can process their stuff in the same way.

Cheers,
Ben

**Comment by KasperSkytte** [comment]
Hi again

Yes it has been om the todo for a while now to make a comprehensive guide to do all the data processing, but thats at one of my collegues desk. I think I found the correct sample IDs so I should be able to get them from our servers and send to the raw reads to you. Ill get back to you next week.

Regards / MVH
Kasper Skytte Andersen

**Comment by KasperSkytte** [comment]
Hi Ben

I have found the raw reads of the samples. I'm not sure exactly which of the samples are used in the data, but you'd be able to tell when analysing it. I haven't been able to find metadata from the sequencing runs, so this is as close as I can get to the raw data. Unfortunately the total size is 26GB, too large to upload anywhere so here's a dropbox link to a zip file with the data: https://www.dropbox.com/s/bzh6ptk2z5kc77x/mmgenome2.zip?dl=0
