### ISSUE TITLE
mmplot - selection

### ISSUE THREAD

**Issue by sarah872** [KasperSkytte/mmgenome2#25]
I am having troubles getting back the coordinates when doing the "selector" argument with `mmplot`. I only have one read set of my sample, so I am plotting the GC value vs Coverage:

```
mmplot(mm, x=mm$cov_testfile.fasta, y=mm$gc, x_scale = "log10", y_limits = c(50,75), x_limits = c(10,10000), locator = TRUE)
```
When running this line, I can draw my polygon, but after clicking `Finish`, only the following error message pops up:
```
Error in names(x) <- value : 
  'names' attribute [54343] must be the same length as the vector [2]
```

**Comment by KasperSkytte** [comment]
Hi there

You need to put the variables in the mm object in quotes. Available ones can be seen with fx `colnames(mm)`. So in your case use `x = “mmplot(mm, cov_testfile.fasta”, y=“gc”, ...)`.

Regards / MVH
Kasper Skytte Andersen

**Comment by KasperSkytte** [comment]
Hi there

You need to put the variables in the mm object in quotes. Available ones can be seen with fx `colnames(mm)`. So in your case use `x = “mmplot(mm, cov_testfile.fasta”, y=“gc”, ...)`.

**Comment by sarah872** [comment]
worked! thanks for the help!
