### ISSUE TITLE
mmgenome2 installing with R 3.6.0

### ISSUE THREAD

**Issue by apoosakkannu** [KasperSkytte/mmgenome2#27]
Hi, I have very new version of the R sotware 3.6.0. I tried to install the mmgenome2 on it. But it seems several of the required packages are not compatible with the latest version. So I have very hard time installing the mmgenome2. Could you pleas help me in this regard! your help is very much appreciated. Thanks in advance.

**Comment by KasperSkytte** [comment]
Hi there

Are you following the installation instructions? I use R 3.6.0, works fine.

Regards
Kasper

**Comment by apoosakkannu** [comment]
Thanks. Yes, I did follow the installation instruction. I have new office windows desktop computer and installed the R3.6.0.

**Comment by KasperSkytte** [comment]
Okay. Can you post the exact commands run and the output from the R console? Preferably using the reprex package, see https://www.tidyverse.org/help/
