### ISSUE TITLE
mmplot coverage heatmap

### ISSUE THREAD

**Issue by Kirk3gaard** [KasperSkytte/mmgenome2#29]
Would be nice to have coverage heatmap option similar to the one in ampvis2 (https://github.com/MadsAlbertsen/ampvis2/blob/master/R/amp_heatmap.R). Grouping contigs by a variable with bin IDs.

**Comment by Kirk3gaard** [comment]
`mmgenome_ampvis_converter <-function(mmgenome_object=NULL,COV_COL_ENDS=NULL,CLASSIFICATION=NULL,BIN_COL=NULL) {
  BIN_COL<-as.name(BIN_COL)
  ### Bins: Calculate abundance for each bin
bins_abundance <- mmgenome_object %>%
  pivot_longer(cols = ends_with(COV_COL_ENDS), names_to = "SeqID", values_to = "Coverage") %>%
  mutate(bp_mapped = length * Coverage) %>%
  group_by_("SeqID", BIN_COL) %>%
  summarise(Mapped = sum(bp_mapped)) %>% 
  select_("SeqID", BIN_COL, "Mapped") %>%
  group_by(SeqID) %>%
  mutate(Abundance=Mapped/sum(Mapped)*100) %>%
  select_("SeqID",BIN_COL, "Abundance") %>%
  pivot_wider(names_from = SeqID, values_from = Abundance)
### Bins: Get taxonomy for each bin (gtdb)
bins_tax<-mmgenome_object %>% select_(BIN_COL, CLASSIFICATION) %>%
  distinct() %>%
  separate_(col = CLASSIFICATION, into = c("Kingdom","Phylum","Class","Order","Family","Genus","Species"), sep = ";") %>% 
  select_(BIN_COL, "Kingdom","Phylum","Class","Order","Family","Genus","Species") %>% filter(!is.na(eval(BIN_COL)))

# Combine TAX+abundance
bins_ampvis_otu<-as.data.frame(bins_abundance %>%
                                 select(as.name(BIN_COL),ends_with(COV_COL_ENDS))) %>%
  left_join(bins_tax) %>%
  dplyr::rename_(OTU=BIN_COL)
bins_ampvis_otu$OTU[which(is.na(bins_ampvis_otu$OTU))]<-"Unbinned"
metadata<- data.frame(SeqID=mmgenome_object %>% select(ends_with(COV_COL_ENDS)) %>% names())
dm <- ampvis2::amp_load(otutable = as.data.frame(bins_ampvis_otu), metadata = metadata)
return(dm)
}

amp_object<-mmgenome_ampvis_converter(mmgenome_object = mmset, COV_COL_ENDS = "_cov", CLASSIFICATION = "gtdb_classification",BIN_COL = "Bin.Id")

ampvis2::amp_heatmap(amp_object, 
            group_by = "SeqID",
            tax_aggregate = "OTU",
            tax_add = "Genus",
            tax_show = 20,
            normalise = F, 
            color_vector = c("white", "red"))`

**Comment by KasperSkytte** [comment]
Nice. You are welcome to make a PR I can review :P Though I think it would be easy to make a separate heatmap function instead of bridging to `ampvis2`. It doesn't need all the extra features in `amp_heatmap` I presume. So basically just a tile plot?

**Comment by Kirk3gaard** [comment]
I have added a pull request to close this issue.

**Comment by KasperSkytte** [comment]
merged
