### ISSUE TITLE
shiny not supported on M1

### ISSUE THREAD

**Issue by jianshu93** [KasperSkytte/mmgenome2#38]
Thank you for using mmgenome2!

If you encounter a problem with mmgenome2 that you are unable to resolve, this is the place for discussing the problem with developers to find a solution. To best help you quickly, please first make sure that:

 - you have the latest version of the package installed
 - you have carefully read the [documentation](https://kasperskytte.github.io/mmgenome2/reference/index.html) of the mmgenome2 function(s) used
 - you have searched the GitHub issues page or the internet for similar or identical problems

Should the problem still persist, then please provide a *minimal* reproducible example, preferably using [reprex](https://www.tidyverse.org/help/#reprex), with self-contained code so that anyone can copy the code and reproduce the problem to easily start debugging without further communication. 

If you suspect that the data used is involved in causing the trouble, then please upload it (preferably a minimal subset) to [figshare](https://figshare.com/) or similar services and provide a link to it. 

all dependencies looks good except shiny for M1 Mac.

Why not remove this. I do not see any reason to use it except interactive plot.

THanks,

Jianshu

**Comment by KasperSkytte** [comment]
Hi Jianshu

What error do you get? You can always emulate x86 architecture and run anything on the M1. `shiny` is essential for the package. The interactive selection of scaffolds is the best way to extract bins. But if you don't need it, I could make it an optional package, that is check for and/or installed when the feature is used.
