### ISSUE TITLE
mmplot_cov_profiles to include scaffold labels

### ISSUE THREAD

**Issue by Kirk3gaard** [KasperSkytte/mmgenome2#6]
Hi

It would be convenient if scaffold names are somehow passed to the points in mmplot_cov_profiles so that it is possible to investigate which scaffolds belong together (using hovering with plotly), without having to make a second plot.

Best regards
Rasmus

**Comment by Kirk3gaard** [comment]
Maybe scaffold size as well

**Comment by KasperSkytte** [comment]
Fixed in 6e4e68eae7c1bcbb0b43931729b344ba8e14ffaa
