### ISSUE TITLE
New Installing problems with R 3.5.1

### ISSUE THREAD

**Issue by chenziwu5** [KasperSkytte/mmgenome2#9]
Hello
I meet a problem below when i installing ‘mmgenome2' with R3.5.1(Rstudio version 1.1.453 ;win10 system 64bit).I follow your proposal and sucessfully installing 'data.table' package before remotes::install_github("kasperskytte/mmgenome2") ,but the problem can not be solved. 
Thank you for your help!

>  remotes::install_github("kasperskytte/mmgenome2")
Downloading GitHub repo kasperskytte/mmgenome2@master
Downloading GitHub repo jkrijthe/Rtsne@openmp
Installing package into ‘C:/Users/user614/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'Rtsne' ...
** libs

*** arch - i386
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'Rtsne'
* removing 'C:/Users/user614/Documents/R/win-library/3.5/Rtsne'
* restoring previous 'C:/Users/user614/Documents/R/win-library/3.5/Rtsne'
In R CMD INSTALL
Downloading GitHub repo Rdatatable/data.table@master
Installing package into ‘C:/Users/user614/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'data.table' ...
** libs

*** arch - i386
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'data.table'
* removing 'C:/Users/user614/Documents/R/win-library/3.5/data.table'
* restoring previous 'C:/Users/user614/Documents/R/win-library/3.5/data.table'
In R CMD INSTALL
Skipping 1 packages ahead of CRAN: data.table
Installing 4 packages: crosstalk, hexbin, htmlwidgets, plotly
package ‘crosstalk’ successfully unpacked and MD5 sums checked
package ‘hexbin’ successfully unpacked and MD5 sums checked
package ‘htmlwidgets’ successfully unpacked and MD5 sums checked
package ‘plotly’ successfully unpacked and MD5 sums checked
Installing package into ‘C:/Users/user614/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'mmgenome2' ...
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Note: possible error in 'layout(margin = list(l = 50, ': 参数没有用[means Parameter is useless](margin = list(l = 50, r = 0, b = 150, t = 20)) 
Note: wrong number of arguments to 'sqrt' 
Note: wrong number of arguments to 'floor' 
** help
*** installing help indices
  converting help for package 'mmgenome2'
    finding HTML links ... 好了[means done]
    mmexpand_network                        html  
    mmexport                                html  
    finding level-2 HTML links ... done

    mmextract                               html  
    mmload                                  html  
    mmlocator                               html  
    mmmerge                                 html  
    mmmerge_linkfiles                       html  
    mmnetwork                               html  
    mmplot                                  html  
    mmplot_cov_profiles                     html  
    mmplot_pairs                            html  
    mmscanbins                              html  
    mmstats                                 html  
    print.ggplot                            html  
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (mmgenome2)
In R CMD INSTALL
Warning messages:
1: In missing_devel_warning(pkgdir) :
  Package Rtsne has compiled code, but no suitable compiler(s) were found. Installation will likely fail.
  Install Rtools and make sure it is in the PATH.
2: In i.p(...) :
  installation of package ‘C:/Users/user614/AppData/Local/Temp/Rtmp4sZBNJ/remotes66586a2b5d2f/jkrijthe-Rtsne-1d0f926’ had non-zero exit status
3: In missing_devel_warning(pkgdir) :
  Package data.table has compiled code, but no suitable compiler(s) were found. Installation will likely fail.
  Install Rtools and make sure it is in the PATH.
4: In i.p(...) :
  installation of package ‘C:/Users/user614/AppData/Local/Temp/Rtmp4sZBNJ/remotes665877f348ba/Rdatatable-data.table-09495c1’ had non-zero exit status

**Comment by KasperSkytte** [comment]
Hi! 

It looks like you have not installed RTools or installed it correctly. It contains the compiler needed to install some of the packages which needs compilation and R cannot find it. When installing RTools, make sure to check the checkbox saying something similar to "add to system PATH" and try again.

 - Kasper

**Comment by chenziwu5** [comment]
thank you for your help!
